src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use DateTime;
use DateTimeZone;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity(fields = {"title"},message ="Le nom du bien existe déjà")
 */
class Property
{

    const HEAT = [
        0 => 'Gaz',
        1 => 'Electrique',
        3 => 'Fioul',
        4 => 'Bois'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * 
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\NotBlank
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min = 10,max = 600,minMessage = "La surface minimum est de 10m²",maxMessage = "La surface maximum est de 600m²")
     * @Assert\NotBlank
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min = 1,max = 15,minMessage = "Le nombre minimum de pièce est de 1",maxMessage = "Le nombre maximum de pièce est de 15")
     * @Assert\NotBlank
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min = 1000,minMessage = "Le prix minimum est de 1000 euros")
     * @Assert\NotBlank
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Type(type="string",message="La ville n'est pas valide.")
     * @Assert\Regex("/^[a-zA-Z]{2}/",message="Nom de ville incorrect")
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, minMessage="Le nombre de caractère minimum est de 5")
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}/",message="Code postal incorrect")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private bool $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity=Picture::class, mappedBy="property", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;

    /**
     * @Assert\All({
     *  @Assert\Image(mimeTypes="image/jpeg")
     * })
     */
    private $pictureFiles;

    /**
     * @ORM\Column(type="float", scale=4, precision=6)
     */
    private $lat;

    /**
     * @ORM\Column(type="float", scale=4, precision=7)
     */
    private $lng;

    public function __construct()
    {
        $this->created_at = new DateTime('now', new DateTimeZone('Europe/Paris'));
        $this->options = new ArrayCollection();
        $this->pictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return ucfirst($this->title);
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return ucfirst($this->description);
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setProperty($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getProperty() === $this) {
                $picture->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * Get })
     *
     * @return array|null
     */
    public function getPictureFiles(): ?array
    {
        return $this->pictureFiles;
    }


    /**
     *
     * @return Picture|null
     */
    public function getPicture(): ?Picture
    {
        return !$this->pictures->isEmpty() ? $this->pictures->first() : null;
    }

    /**
     * Undocumented function
     *
     * @param mixed $pictureFiles
     * @return self
     */
    public function setPictureFiles($pictureFiles): self
    {
        foreach ($pictureFiles as $pictureFile) {
            $picture = new Picture();
            $picture->setImageFile($pictureFile);
            $this->addPicture($picture);
        }
        $this->pictureFiles = $pictureFiles;

        return $this;
    }

    public function getLat(): ?float
    {
        return $this->lat;
    }

    public function setLat(float $lat): self
    {
        $this->lat = $lat;

        return $this;
    }

    public function getLng(): ?float
    {
        return $this->lng;
    }

    public function setLng(float $lng): self
    {
        $this->lng = $lng;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder
            ->add('title', null, ['label' => 'Titre'])
            ->add('description', null, ['label' => 'Description'])
            ->add('surface', null, ['label' => 'Surface'])
            ->add('rooms', null, ['label' => 'Nombre de pièces'])
            ->add('bedrooms', null, ['label' => 'Chambres'])
            ->add('floor', null, ['label' => 'Nombre d\'étage'])
            ->add('price', null, ['label' => 'Prix'])
            ->add('heat', ChoiceType::class, [
                'label' => 'Type de chauffage',
                'choices' => array_flip(Property::HEAT)
            ])
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'choice_label' => 'name',
                'multiple' => true,
                'required' => false
            ])
            ->add('pictureFiles', FileType::class, [
                'required' => false,
                'multiple' => true,
                'label' => 'Ajouter une image',
                'label_attr' => ['data-browse' => 'Parcourir']

            ])
            ->add('city', null, ['label' => 'Ville'])
            ->add('address', null, ['label' => 'Adresse'])
            ->add('postal_code', null, ['label' => 'Code postal'])
            ->add('lat', HiddenType::class)
            ->add('lng', HiddenType::class)
            // Ajoute un champ en fonction de la création ou de l'édition.
            ->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
                $property = $event->getData();
                $form = $event->getForm();
                if ($property->getId())
                    $form->add('sold', null, ['label' => 'Vendu']);
            });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class
        ]);
    }
}

src/Controller/PropertyController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\ContactType;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;

class PropertyController extends AbstractController
{
    /**
     * Affiche la page des biens à vendre
     * @Route("/biens",name="property_index")
     * @return Response
     */
    public function index(PropertyRepository $propertyRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);
        $properties = $paginator->paginate($propertyRepository->findAllSearch($search), $request->query->getInt('page', 1), 12);
        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties',
            'properties' => $properties,
            'form' => $form->createView()

        ]);
    }

    /**
     * @Route("/biens/{slug}-{id}",name="property_show", requirements={"slug": "[a-z0-9\-]*"})
     * @return Response
     */
    public function show(Property $property, string $slug, Request $request, ContactNotification $notification)
    {
        if ($property->getSlug() !== $slug)
            return $this->redirectToRoute('property_show', ['id' => $property->getId(), 'slug' => $property->getSlug()]);
        $contact = new Contact();
        $contact->setProperty($property);
        $form = $this->createForm(ContactType::class, $contact);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $notification->notify($contact);
            $this->addFlash('success', 'Votre message a bien été envoyé');
            return $this->redirectToRoute('property_show', ['id' => $property->getId(), 'slug' => $property->getSlug()]);
        }
        return $this->render('property/show.html.twig', [
            'current_menu' => 'properties',
            'property' => $property,
            'form' => $form->createView()
        ]);
    }
}

templates/property/_property.html.twig
<div class="card mb-4">
	<div class="card-body">
		{% if property.picture %}
			<img src="{{ vich_uploader_asset(property.picture, 'imageFile') | imagine_filter('thumb')}}" alt="" class="card-img-top">
		{% else %}
			<img src="{{ asset('images/empty.jpg') | imagine_filter('thumb') }}" alt="" class="card-img-top">
		{% endif %}
		<h5 class="card-title">
			<a href="{{ path('property_show', {slug: property.slug, id: property.id}) }}">
				{{ property.title }}
			</a>
		</h5>
		<p class="card-text">{{ property.surface}}
			m² -
			{{ property.city}}
			<small>{{ property.postalCode }}</small>
		</p>
		<div class="text-primary" style="font-size:2rem; font-weight:bold">
			{{ property.formattedPrice }}
			€
		</div>
	</div>
</div>

templates/property/index.html.twig
{% extends "base.html.twig" %}
{% block title %}Agence SymfImmo - Tous nos biens
{% endblock %}
{% block body %}
	<div class="jumbotron text-center">
		<h1>Agence SymfImmo - Tous nos biens</h1>
		{{ form_start(form) }}
		<div class="form-row align-items-end mt-4">
			<div class="col">
				{{ form_row(form.minSurface) }}
			</div>
			<div class="col">
				{{ form_row(form.maxPrice) }}
			</div>
			<div class="col">
				{{ form_row(form.options) }}
			</div>
			<div class="col">
				{{ form_row(form.distance) }}
			</div>
			<div class="col">
				<div class="form-group">
					<input type="text" name="" id="search_address" placeholder="Rechercher autour d'une ville" class="form-controle">
				</div>
			</div>
			<div class="col">
				<div class="form-group">
					<button type="submit" class="btn btn-primary">Rechercher</button>
				</div>
			</div>
		</div>
		{{ form_end(form) }}
	</div>
	<div class="container">
		<div class="row">
			{% for property in properties %}
				<div class="col-md-4">
					{% include "property/_property.html.twig" %}
				</div>
			{% endfor %}
		</div>
		<div class="pagination">
			{{ knp_pagination_render(properties) }}
		</div>
	</div>
{% endblock %}

templates/property/show.html.twig
{% extends "base.html.twig" %}

{% block title %}{% endblock %}
{% block body %}
	<div class="jumbotron">
		{% for message in app.flashes('success') %}
			<div class="alert alert-success">{{ message }}</div>
		{% endfor %}
		<div class="container">
			<div class="row">
				<div class="col-md-8">
					<div data-slider>
						{% if property.pictures %}
							{% for picture in property.pictures %}
								<img src="{{ vich_uploader_asset(picture, 'imageFile') | imagine_filter('medium')}}" alt="">
							{% endfor %}
						{% else %}
							<img src="{{ asset('images/empty.jpg') | imagine_filter('medium') }}" alt="">
						{% endif %}
					</div>
				</div>
				<div class="col-md-4">
					<h1>{{ property.title }}</h1>
					<h2>{{ property.rooms }}
						pièces -
						{{property.surface}}
						m²</h2>
					<div class="text-primary" style="font-size: 4rem; font-weight: bold;">{{ property.formattedPrice }}</div>
					<a href="" class="btn btn-primary" id="contactButton" {% if form.vars.submitted %} style="display: none;" {% endif %}>Contacter l'agence</a>
					<div id="contactForm" class="mt-4" {% if not form.vars.submitted %} style="display: none;" {% endif %}>
						{{ form_start(form) }}
						<div class="row">
							<div class="col">{{ form_row(form.firstname) }}</div>
							<div class="col">{{ form_row(form.lastname) }}</div>
						</div>
						<div class="row">
							<div class="col">{{ form_row(form.email) }}</div>
							<div class="col">{{ form_row(form.phone) }}</div>
						</div>
						{{ form_rest(form) }}
						<div class="form-group">
							<button class="btn btn-primary">Envoyer</button>
							<a href="" class="btn btn-primary" id="cancelButton">Annuler</a>
						</div>
						{{ form_end(form) }}
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="container mt-4">
		<p>
			{{ property.description | nl2br }}
		</p>
		<div class="row">
			<div class="col-md-8">
				<h2>Caractéristiques</h2>
				<table class="table table-stripped">
					<tr>
						<td>Surface habitable</td>
						<td>{{ property.surface }}
							m²</td>
					</tr>
					<tr>
						<td>Pièces</td>
						<td>{{ property.rooms }}</td>
					</tr>
					<tr>
						<td>Chambre</td>
						<td>{{ property.bedRooms }}</td>
					</tr>
					<tr>
						<td>Nbre d'étage</td>
						<td>{{ property.floor }}</td>
					</tr>
					<tr>
						<td>Type de chauffage</td>
						<td>{{ property.heatType }}</td>
					</tr>
				</table>
			</div>
			<div class="col-md-4">
				<h2>Spécificités</h2>
				<ul class="list-group">
					{% for option in property.options %}
						<li class="list-group">{{ option.name }}</li>
					{% endfor %}
				</ul>
			</div>
		</div>
		<div id="map" style="width: 100%; height: 400px" data-lat="{{ property.lat }}" data-lng="{{ property.lng }}" class="mb-4"></div>
	</div>
{% endblock %}